apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: iot-monitoring
  labels:
    app: mongodb
spec:
  type: ClusterIP
  ports:
  - port: 27017
    targetPort: 27017
    protocol: TCP
    name: mongodb
  selector:
    app: mongodb
---
apiVersion: v1
kind: Service
metadata:
  name: dashboard-backend
  namespace: iot-monitoring
  labels:
    app: dashboard-backend
spec:
  type: ClusterIP
  sessionAffinity: ClientIP
  ports:
  - port: 5000
    targetPort: 5000
    protocol: TCP
    name: http
  selector:
    app: dashboard-backend
---
apiVersion: v1
kind: Service
metadata:
  name: dashboard-frontend
  namespace: iot-monitoring
  labels:
    app: dashboard-frontend
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: dashboard-frontend
